export const mocks = {
  sizes: [
    { name: "Pequena", price: 28, sabor: 1, fatias: 4 },
    { name: "Média", price: 36, sabor: 2, fatias: 6 },
    { name: "Grande", price: 45.99, sabor: 3, fatias: 8 },
    { name: "Familia", price: 57.99, sabor: 4, fatias: 12 },
  ],
  flavors: [
    { name: "Baurú", desc: "mussarela, frango, tomate, orégano" },
    { name: "Calabresa com catupiry", desc: "mussarela, calabresa, orégano" },
    { name: "Catupiry", desc: "mussarela, catupiry, orégano" },
    { name: "Cheddar", desc: "mussarela, cheddar, orégano" },
    { name: "Dois queijos", desc: "mussarela, provolone, orégano" },
    { name: "Frango", desc: "mussarela, frango, catupiry, orégano" },
    { name: "Mussarela", desc: "molho especial, orégano" },
    { name: "Marguerita", desc: "mussarela, tomate, majericão, orégano" },
    { name: "Milho verde", desc: "mussarela, milho, orégano" },
    { name: "Napolitana", desc: "mussarela, molho, tomate, orégano" },
    { name: "Palmito", desc: "mussarela, palmito, orégano" },
    { name: "Presunto", desc: "mussarela, presunto, orégano" },
    { name: "Portuguesa", desc: "mussarela, presunto, ovos, cebola, orégano" },
    {
      name: "Quatro Queijos",
      desc: "mussarela, provolone, gorgonzola, catupiry, orégano",
    },
    { name: "Siciliana", desc: "mussarela, calabresa, cebola, orégano" },
    { name: "Três Queijos", desc: "mussarela, provolone, catupiry, orégano" },
    {
      name: "Vegetariana",
      desc: "mussarela, ervilha, milho, cebola, tomate, pimentão, azeitonas, orégano",
    },
    { name: "Alemão", desc: "mussarela, frango, bacon, ervilha orégano" },
  ],
  drinks: [
    {
      key: "1",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "2",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "3",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "4",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "5",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "6",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "7",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "8",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "9",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "10",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "11",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "12",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "13",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "14",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "15",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "16",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "17",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "18",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "19",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "20",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
    {
      key: "21",
      name: "Coca-Cola",
      desc: "Sem açucar 220ml",
      priceAfter: 6.8,
      priceBefore: 8,
    },
  ],
};
