name: Front-Deploy

on:
  push:
    branches: [main] # ajuste se usar outra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Criar .env.production
        run: echo "${{ secrets.ENV_PROD_FILE }}" > .env.production

      # 3. Instalar e buildar
      - run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Copiar .env.production para dist/
        run: cp .env.production dist/

      # 4. Enviar apenas dist/ (via rsync --delete)
      - name: Deploy to VPS
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.VPS_DEST }}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_KEY }}

      # 5. (opcional) Reiniciar serviço / clear cache
      - name: Post-deploy command
        if: ${{ env.POST_DEPLOY_CMD != '' }}
        env:
          POST_DEPLOY_CMD: ${{ secrets.POST_DEPLOY_CMD }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "$POST_DEPLOY_CMD"
